package com.appdev.alarmapp.navigation

sealed class Routes(val route:String){
    object Pattern:Routes("Pattern_Screen")
    object GetStarted:Routes("GetStarted")
    object Welcome:Routes("Welcome_Screen")
    object DemoTime:Routes("DemoTime_Screen")
    object ToneSelection:Routes("ringtone_Screen")
    object Setting:Routes("Setting_Screen")
    object Notify:Routes("Notify_Screen")
    object MainScreen:Routes("Main_Screen")
    object MainUIScreen:Routes("MainUI_Screen")
    object SecondScreen:Routes("second_Screen")
    object ThirdScreen:Routes("third_Screen")
    object FourthScreen:Routes("forth_Screen")
    object FifthScreen:Routes("fifth_Screen")
    object Purchase:Routes("purchase_Screen")
    object Preview:Routes("preview_Screen")
    object Ringtone:Routes("Ringtone_Screen")
    object PreviewAlarm:Routes("PreviewAlarm_Screen")
    object MissionScreen:Routes("Mission_Screen")
    object MissionMathScreen:Routes("MissionMath_Screen")
    object MissionShakeScreen:Routes("MissionShake_Screen")
    object SnoozeScreen:Routes("Snooze_Screen")
    object CommonMissionScreen:Routes("CommonMissionScreen_Screen")
    object TypeMissionScreen:Routes("TypeMissionScreen_Screen")
    object SentenceScreen:Routes("SentenceScreen_Screen")
    object MissionMenuScreen:Routes("MissionMenuScreen_Screen")
    object TypingPreviewScreen:Routes("TypingPreviewScreen_Screen")
    object StepDetectorScreen:Routes("StepDetectorScreen_Screen")
    object CameraRoutineScreen:Routes("CameraRoutineScreen_Screen")
    object PhotoClickScreen:Routes("PhotoClickScreen_Screen")
    object PhotoMissionPreviewScreen:Routes("PhotoPreviewScreen_Screen")
    object BarCodeDemoScreen:Routes("BarCodeDemo_Screen")
    object BarCodeScanScreen:Routes("BarCodeScan_Screen")
}